[package]
name = "dhi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dhi-core = { path = "../dhi-core" }
dhi-config = { path = "../dhi-config" }
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
